name: CustomServerTime
version: 1.0.3
api-version: 1.19
author: ShermansWorld
main: me.ShermansWorld.CustomServerTime.Main
commands:
  date:
    description: Displays the server's date
  customservertime:
    description: Admin utility commands